name: Promote dev to main

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  promote:
    uses: Avkroken/.github/.github/workflows/promote-dev-reusable.yml@2b8fe1fb46df1113dc07375e387aa2a8c97e4bc3
    with:
      gamnacken-client-id: ${{ vars.GAMNACKEN_CLIENT_ID }}
    secrets:
      GAMNACKEN_PRIVATE_KEY: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
